stages:
  - setup
  - test

install-reqs:
  stage: setup
  script:
    - pip install --upgrade pip
    - pip install chatterbot


prompt-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running prompt tests..."
    - bash res/gareth_prototyping/testing/run_prompt_tests.sh
    - echo "Finished"
