image:  orvice/chatterbot

stages:
  - setup
  - test

install-reqs:
  stage: setup
  script:
    - pip3 install --upgrade pip
    - pip3 install mysql-connector-python
    - python3 -c "import mysql"
    - pip3 install chatterbot

prompt-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running prompt tests..."
    - pip3 install mysql-connector-python
    - python3 -c "import mysql"
    - bash src/testing/run_prompt_tests.sh
    - echo "Finished"
