image:  orvice/chatterbot

variables:
  PYTHON_VERSION: "3.8.10"

stages:
  - setup
  - test

install-reqs:
  stage: setup
  script:
    - apt-get update -qy
    - apt-get install -y --no-install-recommends git
    - git clone https://github.com/pyenv/pyenv.git ~/.pyenv
    - export PATH="$HOME/.pyenv/bin:$PATH"
    - eval "$(pyenv init -)"
    - eval "$(pyenv virtualenv-init -)"
    - pyenv install $PYTHON_VERSION
    - pyenv global $PYTHON_VERSION
    - export PATH="$HOME/.pyenv/versions/$PYTHON_VERSION/bin:$PATH"
    - python --version  # Verify Python version
    - pip install --upgrade pip
    - pip install mysql-connector-python
    - python3 -c "import mysql.connector ; from mysql.connector import errorcode"

prompt-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - python --version
    - pip install mysql-connector-python # i don't know why this is needed
    - echo "Running prompt tests..."
    - bash src/testing/run_prompt_tests.sh
    - echo "Finished"
